### ISSUE TITLE
Make compound-splitter part of Lucene?

### ISSUE THREAD

**Issue by lukhnos** [dweiss/compound-splitter#5]
Thanks again for having made this module. I was wondering if you have plan to make compound-splitter part of Lucene, or if there are some issues that must be addressed first?

One reason I was wondering this is that there doesn't seem to be much written about the topic (at least in English). And the built-in `HyphenationCompoundWordTokenFilter` and others also don't say much about things like where you can get the dictionary file. compound-splitter appears to be a good, pre-packaged solution for German and perhaps other Germanic languages.

I'm currently using the `GermanCompoundSplitterTokenFilter` found in [a previous PR](https://github.com/dweiss/compound-splitter/pull/1/files) with a customized analyzer (I'm skipping `CustomAnalyzer` because I'm targeting a platform where using Java SPI is cumbersome). I also found that I want to use the compound word analyzer during indexing and highlighting but _not_ querying, as this configuration allows me to find "lerneffekt" with "lern" and "effekt", and it won't give me other words containing "lern" or "effekt" if I search for "lerneffekt" (that would be the case if I also use the compound word analyzer for query, and that would be too noisy to me), but again I'm curious what other people's experiences are.

**Comment by dweiss** [comment]
Scratch your own itch and file a patch to Lucene. I'm not myself a speaker of German, so it's difficult for me to judge how useful it'd be.

**Comment by dweiss** [comment]
Oh, one more thing -- the problem may be in licensing incompatibilities. While the code is APL, the data sets are not. You'd need to consult with Apache Legal about license compatibility.

https://github.com/dweiss/compound-splitter/blob/master/src/data/google-ngrams.LICENSE
https://github.com/dweiss/compound-splitter/blob/master/src/data/morphy.LICENSE

http://www.apache.org/legal/resolved.html
